import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import GlobalNavition from "@/components/layout/navigation/GlobalNavigtion";
import {cookies} from "next/headers";
import {REFRESHTOKEN} from "@/constants/constant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  // const token = cookie.get(ACCESSTOKEN)?.value;
  const response = await fetch(`http://localhost:4000/auth/myprofile`, {
    method: "GET",
    headers: {
      "Content-Type": "application/json",
      authorization: `Bearer ${cookie.get(REFRESHTOKEN)?.value}`,
    },
  });

  const {id} = (await response.json()) as {id: string};

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-full`}
      >
        <GlobalNavition id={Boolean(id)} />
        <main className="flex p-5 h-full">{children}</main>
      </body>
    </html>
  );
}
