import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import GlobalNavition from "@/components/layout/navigation/GlobalNavigtion";
import {cookies} from "next/headers";
import {ACCESSTOKEN} from "@/constants/constant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = await cookies();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-dvh`}
      >
        <GlobalNavition token={cookie.get(ACCESSTOKEN)?.value} />
        <main className="flex flex-col p-5 h-full">{children}</main>
      </body>
    </html>
  );
}
